# Generated by Django 6.0.5 on 2026-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Study', 'Study'), ('Shopping', 'Shopping')], default='Work', max_length=20),
            preserve_default=False,
        ),
    ]
